name: Build & Deploy to GitHub Pages

# Grant write access so the bot can push to gh-pages
permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          VITE_GA_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}

      - name: Copy CNAME
        run: echo "www.themedlinkproject.com" > dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
